version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore Maven Core updates
      - dependency-name: "org.apache.maven:*"
  
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
